# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46788854f998ae96a4b337c35b1e557e8c34c9081e04976bd52c4f25c948621e3f33163ea139a314231148ad6ed4b8c1d446d861538ef29d5e2950928b3edf2a

test:
  secret_key_base: ff1b17656b352d112059cca151c3167c31bb0178efc1a68acc80967cd66eb97cfe269a4a73e71e2cb85b684a6982991f3b57739bdd4d0ea4b35c2fa18a252d12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
